### ISSUE TITLE
time measurements

### ISSUE THREAD

**Issue by wiffel** [jesusfv/Comparison-Programming-Languages-Economics#18]
A little bit late now, but I thought I'll mention it anyway.

I all of the code, you print some progress every 10 iterations. These are executed in the part of the execution that is measured for time. That's not a very good idea. Printing something to the console is very unpredictable. It will or will not block your execution depending on the state of the machine your running the benchmarks on. At least, it will allow for process switches, invalidating your measurements.

Just for the fun of it, I did remove that part and moved the remaining printing outside of the measured part. E.g. for the C++ example that had a 5% effect on the timings. For Julia, it has a 25% effect on the timings.

Since I was busy anyway, I did add '--check-bounds=no' to the Julia command since you also do '-O3' for C++. I also changed 'maximum(abs(...))' to 'max(abs(...))' in the Julia code, since it is available in the base Julia.

These minor changes did reduce the time of both the C++ and the Julia code. But, more importantly, it makes the Julia code run faster then the C++ code. And I guess that changes some of the conclusions in the paper ?

Greetings,
Wilffried
<wiffel@tilient.net>

**Comment by jesusfv** [comment]
Our experience is different. We run the code WITH and WITHOUT the print out of the iterations. We did not experience any significant difference either in time and/or relative performance of the codes.

Sorry for the long time in replying to this. The project was at the desk of an editor for several months and later we were revising the final version for publication.
