### ISSUE TITLE
link in README goes to "Page not found" ?

### ISSUE THREAD

**Issue by bbolker** [jesusfv/Comparison-Programming-Languages-Economics#28]
http://economics.sas.upenn.edu/%7Ejesusfv/comparison_languages.pdf

 Looks like the tilde got mangled somehow: this one works ...

https://economics.sas.upenn.edu/~jesusfv/comparison_languages.pdf

**Comment by jesusfv** [comment]
Not quite sure about this comment. I just checked and I see:

https://economics.sas.upenn.edu/~jesusfv/comparison_languages.pdf

Perhaps an issue with the browser?

**Comment by jesusfv** [comment]
Not quite sure about this comment. I just checked and I see:

https://economics.sas.upenn.edu/~jesusfv/comparison_languages.pdf

Perhaps an issue with the browser?

**Comment by bbolker** [comment]
Works for me in chrome under Ubuntu 16.04 (in a virtualbox) and in chrome 69.0.3497.100  MacOS (El Capitan, 10.11.6); fails under firefox 62.0 on both of the operating systems.
