### ISSUE TITLE
Rcpp comments

### ISSUE THREAD

**Issue by bbolker** [jesusfv/Comparison-Programming-Languages-Economics#29]
I'm not directly involved, but I notice that there's some discussion among Rcpp aficionados [here](http://lists.r-forge.r-project.org/pipermail/rcpp-devel/2018-September/010097.html), suggesting that the `sourceCpp` call [here](https://github.com/jesusfv/Comparison-Programming-Languages-Economics/blob/master/RBC_Rcpp.R#L62) should be moved outside the loop for a fair comparison ...

**Comment by jesusfv** [comment]
Yes, you are right. It was a bad coding idea. I just moved the Rcpp::sourceCpp('InsideLoop.cpp') to outside the while loop. Time in my current Mac goes from around 4.00 seconds to 2.90 seconds (the problem now has more grid points; as to make the testing more interesting with faster computers).

**Comment by bbolker** [comment]
thanks! Some of the people who are more expert on Rcpp may chime in with less trivial ideas about how to improve the performance of the Rcpp implementation ...
